### ISSUE TITLE
Use LNCS bibtex style?

### ISSUE THREAD

**Issue by saucisson** [mpgirro/LNCS-markdown#2]
It does not seem that the bibliography uses the `splncs03` bibliography style. Is there a way to use it?

**Comment by mpgirro** [comment]
Yes, I forgot to add it to the TeX template. Just copy the `splncs03.bst` file into the same directory as everything else, and add the command `\bibliographystyle{splncs03}` to the `lncs-template.tex` file somewhere beneath `\documentclass`. This should do it.

**Comment by saucisson** [comment]
Thanks!
