### ISSUE TITLE
Image, Table, etc. Support

### ISSUE THREAD

**Issue by cansurmeli** [mpgirro/LNCS-markdown#4]
Hi.

It seems that the Markdown file can pass through the LaTeX syntax of tables and images but is it possible to make it work with the markdown syntax of images and tables?

**Comment by mpgirro** [comment]
I know that images work fine. Tables should work too (though I never used it). Basically everything from the Pandoc Markdown specifications should work. Have a look at the [R Markdown documentation](http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html)

**Comment by cansurmeli** [comment]
Yeah, it works. Must've been my mistake not getting it working before.

Thanks 👍🏻
